Feature install angular (#128)
* chore: move all symfony files in server folder

* chore: install angular project and adapt nginx

* feat(front): implement base template

* feat(server): implement api JWT feature

* feat(front): implement Authentication with Angular

  - create a new angular project: public
  - add login logic with cookie creation
  - add auth service

* feat(server): implement authenticated client for unit tests

* chore: add working directory for github action

  - add client ci

diff --git a/.docker/git/pre-commit b/.docker/git/pre-commit
--- a/.docker/git/pre-commit
+++ b/.docker/git/pre-commit
@@ -1,16 +1,19 @@
 #!/bin/bash
 # COMMANDS
 PHP="docker-compose exec -T php php"
+TSLINT="docker-compose exec -T client ./node_modules/.bin/tslint -c ./tslint.json"
 
 # VARIABLES
-PROJECT_DIR=`${PHP} -r "echo dirname(dirname(dirname(realpath('$0'))));"`
+PROJECT_DIR=`${PHP} -r "echo dirname(realpath('$0'), 3);"`
 SERVER_FILES=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep ^server.*\\\\.php`
 PHP_FILES=$(git diff --cached --name-only --diff-filter=ACMR HEAD | grep \.php\$)
+TS_FILES=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep ^client.*\\\\.ts`
 
 # ERROR FLAGS
 ERROR_DUMP=0
 ERROR_PARSE=0
 ERROR_SERVER_CS=0
+ERROR_TS_LINT=0
 
 # COLORS
 GREEN='\e[0;32m'
@@ -54,11 +57,26 @@ if [[ ${ERROR_SERVER_CS} != 0 ]]; then
     echo -e "${RED}Fix ${BROWN}server PHPCS ${RED}errors before commit.${NC}"
 fi
 
+FILES=''
+echo -e "${GREEN}Checking ${BROWN}TSLint${GREEN}...${NC}"
+for file in ${TS_FILES}; do
+    FILES="$FILES $PROJECT_DIR/$file"
+done
+if [[ ! -z "${FILES}" ]]; then
+    ${TSLINT} ${FILES}
+    if [[ $? != 0 ]]; then
+        ERROR_TS_LINT=1
+    fi
+fi
+if [[ ${ERROR_TS_LINT} != 0 ]]; then
+    echo -e "${RED}Fix ${BROWN}TSLint ${GREEN}the error before commit.${NC}"
+fi
+
+
 # Display message and exit status
-! (( $ERROR_DUMP || $ERROR_PARSE || $ERROR_SERVER_CS || $ERROR_ES_LINT || $ERROR_TS_LINT ))
+! (( $ERROR_DUMP || $ERROR_PARSE || $ERROR_SERVER_CS || $ERROR_TS_LINT ))
 ERRORS=$?
 [[ ${ERRORS} == 0 ]] && echo -e "${CYAN}You can commit your job!${NC}"
 [[ ${ERRORS} != 0 ]] && echo -e "${RED}Fix the errors before commit!${NC}"
 
 exit ${ERRORS}
-
